config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :budget_periods
  resources :shortcuts
  resources :ledger_payments, only: [ :new, :create ]
  resources :gateways do
    member do
      post "webhook"
    end
  end
  resources :calendar_notes
  resources :ledger_transfers, only: [ :new, :create ]
  resources :ledger_entry_links
  resources :ledger_tags
  resources :ledgers do
    resources :ownerships, controller: "ledger_ownerships"
    resources :ledger_entries, except: [ :index ] do
      member do
        post "split"
        post "unsplit"
      end
    end
  end
  get "time_kiosk", to: "time_kiosk#index"
  post "time_kiosk", to: "time_kiosk#index"
  patch "time_kiosk", to: "time_kiosk#index"
  resources :checkin_fields
  resources :mailboxes do
    resources :mailbox_messages, except: %i[ index ]
  end
  resources :time_clock_periods
  resources :time_clock_punches, except: :show
  resources :audit_logs, only: %i[ index show destroy ] do
    post "revert", to: "audit_logs#revert", on: :member
  end
  resources :pages
  resources :tokens
  resources :hooks
  resources :badges do
    resources "badge_assignments"
  end
  resources :badge_types
  resources :events do
    resources :checkins, except: %i[ index ]
    member do
      get "arrange"
      get "print"
      patch "field_update", to: "checkins#field_update"
    end
  end
  resources :calendar, only: %i[ index ] do
    collection do
      post "calendar", to: "calendar#calendar"
      get "calendar", to: "calendar#calendar"
    end
  end
  resources :event_types
  resources :announcements
  resources :reports do
    get "run", on: :member
  end
  resources :variables
  resources :teams do
    resources :memberships
  end
  resources :settings, only: %i[ index ] do
    post "update", on: :collection, as: "update"
  end
  resources :team_types
  resources :relationship_types
  resources :people do
    resources :memberships, only: %i[ index new create destroy ]
    resources :relationships, only: %i[ new create destroy ] do
      member do
        post "reverse"
      end
    end
    resource :user, only: %i[ new create edit update ]
    member do
      post "impersonate"
      get "calendar"
      get "statistics"
      get "relationships"
      get "recent_activity"
    end
    collection do
      post "stop_impersonating"
    end
  end

  if Settings[:local_signup]
    devise_for :users, controllers: { omniauth_callbacks: "omniauth", registrations: "users/registrations" }
  else
    devise_for :users, controllers: { omniauth_callbacks: "omniauth" }, skip: :registrations
  end

  get "/setup" => "welcome#setup", as: :setup
  get "search" => "search#index", as: :search
  get "search/combo" => "search#combo", as: :combo_search

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "welcome#index"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  has_neat_id :ann
  include CanBeHooked
  has_paper_trail versions: { class_name: "AuditLog" }
  belongs_to :team, optional: true

  attr_accessor :notify_now

  validates :title, presence: true
  validates :content, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  scope :visible, -> { where("start_time < ? AND end_time > ?", DateTime.current, DateTime.current) }

  def self.ransackable_attributes(auth_object = nil)
    [ "title", "content", "start_time", "end_time", "team_id", "updated_at" ]
  end

  def self.ransackable_associations(auth_objects = nil)
    [ "team" ]
  end

  def identifier_icon
    "comment"
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < InternalController
  before_action :set_announcement, only: %i[ show edit update destroy ]

  # GET /announcements
  def index
    @q = policy_scope(Announcement).ransack(params[:q])
    @q.sorts = "start_time asc" if @q.sorts.empty?
    @announcements = @q.result(distinct: true).order(end_time: :asc, start_time: :asc).page(params[:page])
  end

  # GET /announcements/1
  def show
  end

  # GET /announcements/new
  def new
    @announcement = authorize Announcement.new(start_time: Time.current, end_time: Time.current + 1.week)
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  def create
    @announcement = authorize Announcement.new(announcement_params)

    if @announcement.save
      AnnouncementNotificationRouter.new(@announcement).run
      redirect_to @announcement, notice: "Announcement was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /announcements/1
  def update
    if @announcement.update(announcement_params)
      AnnouncementNotificationRouter.new(@announcement).run
      redirect_to @announcement, notice: "Announcement was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /announcements/1
  def destroy
    @announcement.destroy!
    redirect_to announcements_url, notice: "Announcement was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = policy_scope(Announcement).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:title, :content, :start_time, :end_time, :team_id, :notify_now)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.erb
<div class="card" id="<%= dom_id announcement %>">
  <div class="card-header">
    <% if announcement.team %>
      <%= link_to i(announcement.team.team_type.icon), team_path(announcement.team), class: "badge rounded-pill", style: "background-color:#{announcement.team.color};color:#{contrasting_color(announcement.team.color)}", "data-turbo": "false", title: "Posted in #{announcement.team.name}" %>
    <% end %>
    <%= link_to announcement.title, announcement, "data-turbo": "false" %>
  </div>
  <div class="card-body">
    <%= announcement.content %>
  </div>
</div>

app/views/announcements/_form.html.erb
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <div class="row">
    <div class="col-12 col-md-6">
      <%= f.input :title %>
    </div>
    <div class="col-12 col-md-6">
      <%= f.input :team_id, as: :searching_combobox, label: 'Team', scope: "managed_teams", include_blank: admin?, required: !admin? %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-md-5">
      <%= f.input :start_time %>
    </div>
    <div class="col-12 col-md-5">
      <%= f.input :end_time %>
    </div>
    <div class="col-12 col-md-2">
      <%= f.input :notify_now, as: :boolean %>
    </div>
  </div>
  
  <%= f.input :content, wrapper_html: { class: 'code-editor' }, input_html: { rows: 6, data: { lang: "markdown" } } %>
  
  
</div>

app/views/announcements/edit.html.erb
<% breadcrumb @announcement %>

<%= simple_form_for(@announcement) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Editing <%= @announcement.identifier_name %></h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", @announcement, class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/announcements/index.html.erb
<% breadcrumb :announcements %>

<%= search_form_for @q, data: {"controller": "turbo_search", "turbo_frame": "results"} do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Announcements</h1>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md">
        <%= f.input :title_i_cont, label: 'Title' %>
      </div>
      <div class="col-md">
        <%= f.input :content_i_cont, label: 'Content' %>
      </div>
      <div class="col-md">
        <%= f.input :team_id_eq, label: 'Team', as: :select, collection: policy_scope(Team) %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "New Announcement", new_announcement_path, class: 'btn btn-success' if policy(Announcement).create? %>
    <%= f.submit 'Search', class: 'btn btn-primary', data: { action: "turbo_search#search" } %>
    <%= link_to 'Clear Search', request.path, class: "btn btn-dark", data: { action: "turbo_search#clear" } %>
  </div>
</div>
<% end %>

<%= turbo_frame_tag "results" do %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Sort By
    </button>
    <ul class="dropdown-menu">
      <li><%= sort_link @q, :title, "Title", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :start_time, "Start Time", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :end_time, "End Time", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :updated_at, "Last Updated", class: "dropdown-item" %></li>
    </ul>
  </div>

  <div id="announcements" class="row">
    <% @announcements.each do |announcement| %>
      <div class="col-12 col-md-6">
        <div class="card" id="<%= dom_id announcement %>">
          <div class="card-header">
            <% if announcement.team %>
              <%= link_to i(announcement.team.team_type.icon), team_path(announcement.team), class: "badge rounded-pill", style: "background-color:#{announcement.team.color};color:#{contrasting_color(announcement.team.color)}", "data-turbo": "false", title: "Posted in #{announcement.team.name}" %>
            <% end %>
            <%= link_to announcement.title, announcement, "data-turbo": "false" %>
          </div>
          <div class="card-body">
            <%= md announcement.content.truncate(80) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= paginate @announcements %>
<% end %>

app/views/announcements/new.html.erb
<% breadcrumb @announcement %>

<%= simple_form_for(@announcement) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>New announcement</h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", announcements_path, class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/announcements/show.html.erb
<% breadcrumb @announcement %>

<div class="card">
  <div class="card-header">
    <h1>
      <% if @announcement.team %>
        <%= link_to i(@announcement.team.team_type.icon), team_path(@announcement.team), class: "badge rounded-pill", style: "background-color:#{@announcement.team.color};color:#{contrasting_color(@announcement.team.color)}", "data-turbo": "false", title: "Posted in #{@announcement.team.name}" %>&nbsp;
      <% end %>
      <%= @announcement.title %>
    </h1>
  </div>
  <div class="card-body">
    <p>
      <em>Runs from <%= nice_datetime_range @announcement.start_time, @announcement.end_time %></em>
    </p>
    <%= md @announcement.content %>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_announcement_path(@announcement), class: 'btn btn-warning' if policy(@announcement).update? %>
    <%= link_to 'Delete', @announcement, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if policy(@announcement).destroy? %>
  </div>
</div>