config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :budget_periods
  resources :shortcuts
  resources :ledger_payments, only: [ :new, :create ]
  resources :gateways do
    member do
      post "webhook"
    end
  end
  resources :calendar_notes
  resources :ledger_transfers, only: [ :new, :create ]
  resources :ledger_entry_links
  resources :ledger_tags
  resources :ledgers do
    resources :ownerships, controller: "ledger_ownerships"
    resources :ledger_entries, except: [ :index ] do
      member do
        post "split"
        post "unsplit"
      end
    end
  end
  get "time_kiosk", to: "time_kiosk#index"
  post "time_kiosk", to: "time_kiosk#index"
  patch "time_kiosk", to: "time_kiosk#index"
  resources :checkin_fields
  resources :mailboxes do
    resources :mailbox_messages, except: %i[ index ]
  end
  resources :time_clock_periods
  resources :time_clock_punches, except: :show
  resources :audit_logs, only: %i[ index show destroy ] do
    post "revert", to: "audit_logs#revert", on: :member
  end
  resources :pages
  resources :tokens
  resources :hooks
  resources :badges do
    resources "badge_assignments"
  end
  resources :badge_types
  resources :events do
    resources :checkins, except: %i[ index ]
    member do
      get "arrange"
      get "print"
      patch "field_update", to: "checkins#field_update"
    end
  end
  resources :calendar, only: %i[ index ] do
    collection do
      post "calendar", to: "calendar#calendar"
      get "calendar", to: "calendar#calendar"
    end
  end
  resources :event_types
  resources :announcements
  resources :reports do
    get "run", on: :member
  end
  resources :variables
  resources :teams do
    resources :memberships
  end
  resources :settings, only: %i[ index ] do
    post "update", on: :collection, as: "update"
  end
  resources :team_types
  resources :relationship_types
  resources :people do
    resources :memberships, only: %i[ index new create destroy ]
    resources :relationships, only: %i[ new create destroy ] do
      member do
        post "reverse"
      end
    end
    resource :user, only: %i[ new create edit update ]
    member do
      post "impersonate"
      get "calendar"
      get "statistics"
      get "relationships"
      get "recent_activity"
    end
    collection do
      post "stop_impersonating"
    end
  end

  if Settings[:local_signup]
    devise_for :users, controllers: { omniauth_callbacks: "omniauth", registrations: "users/registrations" }
  else
    devise_for :users, controllers: { omniauth_callbacks: "omniauth" }, skip: :registrations
  end

  get "/setup" => "welcome#setup", as: :setup
  get "search" => "search#index", as: :search
  get "search/combo" => "search#combo", as: :combo_search

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "welcome#index"
end

app/models/membership.rb
class Membership < ApplicationRecord
  has_neat_id :mbr
  include CanBeHooked
  has_paper_trail versions: { class_name: "AuditLog" }
  belongs_to :person
  belongs_to :team

  def self.ransackable_attributes(auth_object = nil)
    [ "manager", "person.display_name", "person.last_name", "person.first_name", "person.birthday", "updated_at" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "person" ]
  end

  def identifier_icon
  end

  def identifier_name
    "#{person.display_name} => #{team.name}"
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < InternalController
  before_action :set_team_or_person
  before_action :set_membership, only: %i[ show edit update destroy ]

  # GET /memberships
  def index
    @q = false
    if @team
      @q = policy_scope(Membership).where(team: @team).ransack(params[:q])
    elsif @person
      @q = policy_scope(Membership).where(person: @person).ransack(params[:q])
    end
    @memberships = @q.result(distinct: true).includes(:person).includes(:team).order("person.last_name" => "desc", "team.name" => "asc").page(params[:page])
    if @team
      render "by_team"
    elsif @person
      render "by_person"
    end
  end

  def show
  end

  def new
    @membership = authorize (@team || @person).memberships.build
  end

  # POST /memberships
  def create
    @membership = authorize (@team || @person).memberships.build(membership_params)

    if @membership.save
      target = if @team
        team_memberships_path(@team)
      else
        person_memberships_path(@person)
      end
      redirect_to target, notice: "Membership was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  # PATCH/PUT /memberships/1
  def update
    target = if @team
      team_memberships_path(@team)
    else
      person_memberships_path(@person)
    end
    if @membership.update(membership_params)
      redirect_to target, notice: "Membership was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /memberships/1
  def destroy
    target = if @team
        team_memberships_path(@team)
      else
        person_memberships_path(@person)
      end
    @membership.destroy!
    redirect_to target, notice: "Membership was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_or_person
      @team = policy_scope(Team).find(params[:team_id]) if params[:team_id]
      @person = policy_scope(Person).find(params[:person_id]) if params[:person_id]
    end

    def set_membership
      @membership = authorize (@team || @person).memberships.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.require(:membership).permit(:person_id, :team_id, :manager)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
  def membership_as_badge(membership, **opts)
    content = i(membership.manager ? "user-tie" : "user") + " " + membership.team.name
    link_to [ membership.team, membership ] do
      tag.span content, class: "badge", style: "background-color: #{membership.team.color}; color: #{contrasting_color(membership.team.color)}"
    end
  end
end

app/views/memberships/_form.html.erb
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <div class="row align-items-center">
    <div class="col-12 col-md-4">
      <% if f.object.persisted? || @person %>
      <label class="form-label">Person</label>
        <input disabled type="text" value="<%= f.object.person.identifier_name %>" class="form-control" />
      <% else %>
        <%= f.input :person_id, as: :searching_combobox, scope: 'managed_people' %>
      <% end %>
    </div>
    <div class="col-12 col-md-4">
      <% if f.object.persisted? || @team %>
      <label class="form-label">Team</label>
        <input disabled type="text" value="<%= f.object.team.identifier_name %>" class="form-control" />
      <% else %>
        <%= f.input :team_id, as: :searching_combobox, scope: 'managed_teams' %>
      <% end %>
    </div>
    <div class="col-6 col-md-4">
      <%= f.input :manager, label: 'Manager?' %>
    </div>
  </div>
  
  
</div>

app/views/memberships/_membership.html.erb
<div class="card" id="<%= dom_id membership %>">
  <div class="card-header">
    <% if membership.manager %>
      <span title="Manager"><%= i 'user-tie'%></span>
    <% end %>
    <%= link_to membership.person.identifier_name, [membership.team, membership], "data-turbo": "false" %>
  </div>
  <div class="card-body">
    <%= image_tag get_avatar_url(membership.person.avatar), class: 'person-img' %>
  </div>
</div>

app/views/memberships/by_person.html.erb
<%= render "people/show_shared" %>

<div class="card">
  <div class="card-header">
    <h1><%= @person.identifier_name %></h1>
  </div>
  <div class="card-body">
    <h2>Team Memberships</h2>

    <% if @person&.user&.architect %>
      <div class="alert alert-danger">
        <span class="badge fs-3" title="Site Architect" style="background-color: black; color: #d52; border: thick solid #b21;"><%= i 'screwdriver-wrench' %></span>
        This person is an architect and has full manager access to all teams.
      </div>
    <% elsif @person&.user&.admin %>
      <div class="alert alert-warning">
        <span class="badge fs-3" title="Site Admin" style="background-color: black; color: #dd2; border: thick solid #bb1;"><%= i 'crown' %></span>
        This person is an admin and has full manager access to all teams.
      </div>
    <% end %>

    <% @memberships.each do |m| %>
      <div class="row align-items-center my-3">
        <div class="col-6 col-lg-3 fs-4 text-end">
          <div class="<%= "manager" if @person.managed_teams.include? m.team %>">
            <%= link_to as_badge(m.team), m.team %>
          </div>
        </div>
        <div class="col-md-3">
          <% if m.team.parent.present? %>
            Grants membership in:
            <% p = m.team %>
            <div class="badge-container">
              <% while p = p.parent %>
                <%= link_to as_badge(p), p %>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="col-md-3">
          <% if m.manager? && m.team.children.present? %>
            Grants manager powers in:
            <div class="badge-container">
              <% m.team.children.order(name: :asc).each do |child_team| %>
                <%= link_to as_badge(child_team), child_team %>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="col">
          <%= link_to 'Delete', [@person, m], class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if policy(m).destroy? %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Add Membership', new_person_membership_path(@person), class: 'btn btn-info' %>
  </div>
</div>

app/views/memberships/by_team.html.erb
<% breadcrumb :memberships, @team %>

<%= search_form_for @q, url: team_memberships_path(@team), data: {"controller": "turbo_search", "turbo_frame": "results"} do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Direct Memberships</h1>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md">
        <%= f.input :person_display_name_cont, label: 'Name' %>
      </div>
      <div class="col-md">
        <%= f.input :manager_eq, label: 'Manager?', as: :select, collection: [['Yes', true], ['No', false]], include_blank: true %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Add Member', new_team_membership_path(@team), class: 'btn btn-success' %>
    <%= f.submit 'Search', class: 'btn btn-primary', data: { action: "turbo_search#search" } %>
    <%= link_to 'Clear Search', request.path, class: "btn btn-dark", data: { action: "turbo_search#clear" } %>
  </div>
</div>
<% end %>

<%= turbo_frame_tag "results" do %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Sort By
    </button>
    <ul class="dropdown-menu">
      <li><%= sort_link @q, :manager, "Manager Status", class: "dropdown-item", default_order: :desc %></li>
      <li><%= sort_link @q, :last_name, "Last Name", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :first_name, "First Name", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :birthday, "Age", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :updated_at, "Last Updated", class: "dropdown-item" %></li>
    </ul>
  </div>

  <div id="people" class="row">
    <% @memberships.each do |membership| %>
      <div class="col-6 col-md-2">
        <%= render membership %>
      </div>
    <% end %>
  </div>

  <%= paginate @memberships %>
<% end %>

app/views/memberships/edit.html.erb
<% breadcrumb @membership, (@team || @person) %>

<%= simple_form_for([(@team || @person), @membership]) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Editing <%= @membership.identifier_name %></h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", [(@team || @person), @membership], class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/memberships/index.html.erb
<% breadcrumb :memberships, @team %>

<%= search_form_for @q, url: team_memberships_path(@team), data: {"controller": "turbo_search", "turbo_frame": "results"} do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Direct Memberships</h1>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md">
        <%= f.input :person_display_name_cont, label: 'Name' %>
      </div>
      <div class="col-md">
        <%= f.input :manager_eq, label: 'Manager?', as: :select, collection: [['Yes', true], ['No', false]], include_blank: true %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Add Member', new_team_membership_path(@team), class: 'btn btn-success' %>
    <%= f.submit 'Search', class: 'btn btn-primary', data: { action: "turbo_search#search" } %>
    <%= link_to 'Clear Search', request.path, class: "btn btn-dark", data: { action: "turbo_search#clear" } %>
  </div>
</div>
<% end %>

<%= turbo_frame_tag "results" do %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Sort By
    </button>
    <ul class="dropdown-menu">
      <li><%= sort_link @q, :manager, "Manager Status", class: "dropdown-item", default_order: :desc %></li>
      <li><%= sort_link @q, :last_name, "Last Name", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :first_name, "First Name", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :birthday, "Age", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :updated_at, "Last Updated", class: "dropdown-item" %></li>
    </ul>
  </div>

  <div id="people" class="row">
    <% @memberships.each do |membership| %>
      <div class="col-6 col-md-2">
        <%= render membership %>
      </div>
    <% end %>
  </div>

  <%= paginate @memberships %>
<% end %>

app/views/memberships/new.html.erb
<% breadcrumb @membership, (@team || @person) %>

<%= simple_form_for([(@team || @person), @membership]) do |f| %>
  <div class="card">
    <div class="card-header">
      <h1>New membership</h1>
    </div>
    <div class="card-body">
      <%= render "form", f: f %>
    </div>
    <div class="card-footer">
      <% target = if @team
        team_memberships_path(@team)
      else
        person_memberships_path(@person)
      end %>
      <%= link_to "Cancel", target, class: 'btn btn-warning' %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/memberships/show.html.erb
<% breadcrumb @membership, @team || @person %>

<div class="card">
  <div class="card-header">
    <h1><%= @membership.identifier_name %></h1>
  </div>
  <div class="card-body">
    <div class="row align-items-center">
      <div class="col-md-2">
        <%= link_to image_tag(get_avatar_url(@membership.person.avatar), class: 'person-img'), person_path(@membership.person) %>
      </div>
      <div class="col-md-6">
        <p>
          <%= link_to @membership.person.display_name, person_path(@membership.person) %> is a <%= @membership.manager? ? 'manager' : 'member' %> of <%= as_badge @membership.team %>
        </p>

        <% if @membership.team.parent.present? %>
            <p>
              That means <%= @membership.person.display_name %> is also a member of:
            </p>
          <% p = @membership.team %>
          <div class="badge-container">
            <% while p = p.parent %>
              <%= as_badge p %>
            <% end %>
          </div>
        <% end %>

        <% if @membership.manager? && @membership.team.children.present? %>
          <p>
            That means <%= @membership.person.display_name %> can also manage:
          </p>
          <div class="badge-container">
            <% @membership.team.children.order(name: :asc).each do |child_team| %>
              <%= as_badge child_team %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-md-4">
        <p><%= @membership.person.display_name %> has <%= pluralize @membership.person.memberships.count - 1, 'other membership' %>.</p>
        <div class="badge-container">
          <% @membership.person.memberships.each do |membership| %>
            <%= as_badge membership unless membership == @membership %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_team_membership_path(@team, @membership), class: 'btn btn-warning' %>
    <%= link_to 'Delete', [@team, @membership], class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>