config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :budget_periods
  resources :shortcuts
  resources :ledger_payments, only: [ :new, :create ]
  resources :gateways do
    member do
      post "webhook"
    end
  end
  resources :calendar_notes
  resources :ledger_transfers, only: [ :new, :create ]
  resources :ledger_entry_links
  resources :ledger_tags
  resources :ledgers do
    resources :ownerships, controller: "ledger_ownerships"
    resources :ledger_entries, except: [ :index ] do
      member do
        post "split"
        post "unsplit"
      end
    end
  end
  get "time_kiosk", to: "time_kiosk#index"
  post "time_kiosk", to: "time_kiosk#index"
  patch "time_kiosk", to: "time_kiosk#index"
  resources :checkin_fields
  resources :mailboxes do
    resources :mailbox_messages, except: %i[ index ]
  end
  resources :time_clock_periods
  resources :time_clock_punches, except: :show
  resources :audit_logs, only: %i[ index show destroy ] do
    post "revert", to: "audit_logs#revert", on: :member
  end
  resources :pages
  resources :tokens
  resources :hooks
  resources :badges do
    resources "badge_assignments"
  end
  resources :badge_types
  resources :events do
    resources :checkins, except: %i[ index ]
    member do
      get "arrange"
      get "print"
      patch "field_update", to: "checkins#field_update"
    end
  end
  resources :calendar, only: %i[ index ] do
    collection do
      post "calendar", to: "calendar#calendar"
      get "calendar", to: "calendar#calendar"
    end
  end
  resources :event_types
  resources :announcements
  resources :reports do
    get "run", on: :member
  end
  resources :variables
  resources :teams do
    resources :memberships
  end
  resources :settings, only: %i[ index ] do
    post "update", on: :collection, as: "update"
  end
  resources :team_types
  resources :relationship_types
  resources :people do
    resources :memberships, only: %i[ index new create destroy ]
    resources :relationships, only: %i[ new create destroy ] do
      member do
        post "reverse"
      end
    end
    resource :user, only: %i[ new create edit update ]
    member do
      post "impersonate"
      get "calendar"
      get "statistics"
      get "relationships"
      get "recent_activity"
    end
    collection do
      post "stop_impersonating"
    end
  end

  if Settings[:local_signup]
    devise_for :users, controllers: { omniauth_callbacks: "omniauth", registrations: "users/registrations" }
  else
    devise_for :users, controllers: { omniauth_callbacks: "omniauth" }, skip: :registrations
  end

  get "/setup" => "welcome#setup", as: :setup
  get "search" => "search#index", as: :search
  get "search/combo" => "search#combo", as: :combo_search

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "welcome#index"
end

app/controllers/badge_types_controller.rb
class BadgeTypesController < InternalController
  before_action :set_badge_type, only: %i[ show edit update destroy ]

  # GET /badge_types
  def index
    @q = policy_scope(BadgeType).ransack(params[:q])
    @q.sorts = "name asc" if @q.sorts.empty?
    @badge_types = @q.result(distinct: true).order(name: :asc).page(params[:page])
  end

  # GET /badge_types/1
  def show
  end

  # GET /badge_types/new
  def new
    @badge_type = authorize BadgeType.new
  end

  # GET /badge_types/1/edit
  def edit
  end

  # POST /badge_types
  def create
    @badge_type = authorize BadgeType.new(badge_type_params)

    if @badge_type.save
      redirect_to @badge_type, notice: 'Badge type was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /badge_types/1
  def update
    if @badge_type.update(badge_type_params)
      redirect_to @badge_type, notice: 'Badge type was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /badge_types/1
  def destroy
    @badge_type.destroy!
    redirect_to badge_types_url, notice: 'Badge type was successfully destroyed.', status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge_type
      @badge_type = policy_scope(BadgeType).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def badge_type_params
      params.require(:badge_type).permit(:name)
    end
end

app/helpers/badge_types_helper.rb
module BadgeTypesHelper
end

app/views/badge_types/_badge_type.html.erb
<div class="card" id="<%= dom_id badge_type %>">
  <div class="card-header">
    <%= link_to badge_type.identifier_name, badge_type, "data-turbo": "false" %>
  </div>
</div>

app/views/badge_types/_form.html.erb
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :name %>
</div>

app/views/badge_types/edit.html.erb
<% breadcrumb @badge_type %>

<%= simple_form_for(@badge_type) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Editing <%= @badge_type.identifier_name %></h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", @badge_type, class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/badge_types/index.html.erb
<% breadcrumb :badge_types %>

<%= search_form_for @q, data: {"controller": "turbo_search", "turbo_frame": "results"} do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Badge Types</h1>
  </div>
  <div class="card-body">
    <%= f.input :name_cont, label: 'Name' %>
  </div>
  <div class="card-footer">
    <%= link_to "New Badge Type", new_badge_type_path, class: 'btn btn-success' if policy(BadgeType).new? %>
    <%= f.submit 'Search', class: 'btn btn-primary', data: { action: "turbo_search#search" } %>
    <%= link_to 'Clear Search', request.path, data: { action: "turbo_search#clear" }, class: "btn btn-dark" %>
  </div>
</div>
<% end %>

<%= turbo_frame_tag "results" do %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Sort By
    </button>
    <ul class="dropdown-menu">
      <li><%= sort_link @q, :name, "Name", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :updated_at, "Last Updated", class: "dropdown-item" %></li>
    </ul>
  </div>

  <div id="badge_types" class="row">
    <% @badge_types.each do |badge_type| %>
      <div class="col-md-3">
        <%= render badge_type %>
      </div>
    <% end %>
  </div>

  <%= paginate @badge_types %>
<% end %>

app/views/badge_types/new.html.erb
<% breadcrumb @badge_type %>

<%= simple_form_for(@badge_type) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>New badge type</h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", badge_types_path, class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/badge_types/show.html.erb
<% breadcrumb @badge_type %>

<div class="card">
  <div class="card-header">
    <h1><%= @badge_type.identifier_name %></h1>
  </div>
  <div class="card-body">
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_badge_type_path(@badge_type), class: 'btn btn-warning' %>
    <%= link_to 'Delete', @badge_type, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>