config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :budget_periods
  resources :shortcuts
  resources :ledger_payments, only: [ :new, :create ]
  resources :gateways do
    member do
      post "webhook"
    end
  end
  resources :calendar_notes
  resources :ledger_transfers, only: [ :new, :create ]
  resources :ledger_entry_links
  resources :ledger_tags
  resources :ledgers do
    resources :ownerships, controller: "ledger_ownerships"
    resources :ledger_entries, except: [ :index ] do
      member do
        post "split"
        post "unsplit"
      end
    end
  end
  get "time_kiosk", to: "time_kiosk#index"
  post "time_kiosk", to: "time_kiosk#index"
  patch "time_kiosk", to: "time_kiosk#index"
  resources :checkin_fields
  resources :mailboxes do
    resources :mailbox_messages, except: %i[ index ]
  end
  resources :time_clock_periods
  resources :time_clock_punches, except: :show
  resources :audit_logs, only: %i[ index show destroy ] do
    post "revert", to: "audit_logs#revert", on: :member
  end
  resources :pages
  resources :tokens
  resources :hooks
  resources :badges do
    resources "badge_assignments"
  end
  resources :badge_types
  resources :events do
    resources :checkins, except: %i[ index ]
    member do
      get "arrange"
      get "print"
      patch "field_update", to: "checkins#field_update"
    end
  end
  resources :calendar, only: %i[ index ] do
    collection do
      post "calendar", to: "calendar#calendar"
      get "calendar", to: "calendar#calendar"
    end
  end
  resources :event_types
  resources :announcements
  resources :reports do
    get "run", on: :member
  end
  resources :variables
  resources :teams do
    resources :memberships
  end
  resources :settings, only: %i[ index ] do
    post "update", on: :collection, as: "update"
  end
  resources :team_types
  resources :relationship_types
  resources :people do
    resources :memberships, only: %i[ index new create destroy ]
    resources :relationships, only: %i[ new create destroy ] do
      member do
        post "reverse"
      end
    end
    resource :user, only: %i[ new create edit update ]
    member do
      post "impersonate"
      get "calendar"
      get "statistics"
      get "relationships"
      get "recent_activity"
    end
    collection do
      post "stop_impersonating"
    end
  end

  if Settings[:local_signup]
    devise_for :users, controllers: { omniauth_callbacks: "omniauth", registrations: "users/registrations" }
  else
    devise_for :users, controllers: { omniauth_callbacks: "omniauth" }, skip: :registrations
  end

  get "/setup" => "welcome#setup", as: :setup
  get "search" => "search#index", as: :search
  get "search/combo" => "search#combo", as: :combo_search

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "welcome#index"
end

app/models/report.rb
class Report < ApplicationRecord
  has_neat_id :rpt
  has_paper_trail versions: { class_name: "AuditLog" }

  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[ name updated_at ]
  end

  def identifier_icon
    "file-code"
  end
end

app/controllers/reports_controller.rb
class ReportsController < InternalController
  before_action :set_report, only: %i[ show run edit update destroy ]

  # GET /reports
  def index
    @q = Report.ransack(params[:q])
    @q.sorts = "name asc" if @q.sorts.empty?
    @reports = @q.result(distinct: true).order(name: :asc).page(params[:page])
  end

  # GET /reports/1
  def show
  end

  # GET /reports/1/run
  def run
    @results = JSON.pretty_generate(eval(@report.code))
  end

  # GET /reports/new
  def new
    @report = authorize Report.new
  end

  # GET /reports/1/edit
  def edit
    authorize @report
  end

  # POST /reports
  def create
    @report = authorize Report.new(report_params)

    if @report.save
      redirect_to @report, notice: "Report was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reports/1
  def update
    authorize @report
    if @report.update(report_params)
      redirect_to @report, notice: "Report was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy!
    redirect_to reports_url, notice: "Report was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:name, :code)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<%= f.input :name %>
<%= f.input :code, wrapper_html: { class: 'code-editor' }, input_html: { rows: 12, data: { lang: "ruby" } } %>

app/views/reports/_report.html.erb
<div class="card" id="<%= dom_id report %>">
  <div class="card-header">
    <%= link_to report.identifier_name, report, "data-turbo": "false" %>
  </div>
  <div class="card-footer">
    <%= link_to 'Run', run_report_path(report), class: 'btn btn-sm btn-success', "data-turbo": "false" %>
  </div>
</div>

app/views/reports/edit.html.erb
<% breadcrumb @report %>

<%= simple_form_for(@report) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Editing <%= @report.identifier_name %></h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", @report, class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/reports/index.html.erb
<% breadcrumb :reports %>

<%= search_form_for @q, data: {"controller": "turbo_search", "turbo_frame": "results"} do |f| %>
<div class="card">
  <div class="card-header">
    <h1>Reports</h1>
  </div>
  <div class="card-body">
    <%= f.input :name_i_cont, label: 'Name' %>
  </div>
  <div class="card-footer">
    <%= link_to "New Report", new_report_path, class: 'btn btn-success' if policy(Report).new? %>
    <%= f.submit 'Search', class: 'btn btn-primary', data: { action: "turbo_search#search" } %>
    <%= link_to 'Clear Search', request.path, class: "btn btn-dark", data: { action: "turbo_search#clear" } %>
  </div>
</div>
<% end %>

<%= turbo_frame_tag "results" do %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Sort By
    </button>
    <ul class="dropdown-menu">
      <li><%= sort_link @q, :name, "Name", class: "dropdown-item" %></li>
      <li><%= sort_link @q, :updated_at, "Last Updated", class: "dropdown-item" %></li>
    </ul>
  </div>

  <div id="reports" class="row">
    <% @reports.each do |report| %>
      <div class="col-md-3">
        <%= render report %>
      </div>
    <% end %>
  </div>

  <%= paginate @reports %>
<% end %>

app/views/reports/new.html.erb
<% breadcrumb @report %>

<%= simple_form_for(@report) do |f| %>
<div class="card">
  <div class="card-header">
    <h1>New report</h1>
  </div>
  <div class="card-body">
    <%= render "form", f: f %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", reports_path, class: 'btn btn-warning' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/reports/run.html.erb
<% breadcrumb :run, @report %>

<div class="card">
  <div class="card-header">
    <h1><%= @report.identifier_name %></h1>
  </div>
  <div class="card-body">
    <code><pre><%= @results %></pre></code>
  </div>
  <div class="card-footer">
    <%= link_to 'Show Code', @report, class: 'btn btn-info' %>
    <%= link_to 'Run', run_report_path(@report), class: 'btn btn-success' %>
    <%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-warning' %>
    <%= link_to 'Delete', @report, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/reports/show.html.erb
<% breadcrumb @report %>

<div class="card">
  <div class="card-header">
    <h1><%= @report.identifier_name %></h1>
  </div>
  <div class="card-body">
    <code data-lang="ruby"><pre><%= @report.code %></pre></code>
  </div>
  <div class="card-footer">
    <%= link_to 'Run', run_report_path(@report), class: 'btn btn-success' %>
    <%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-warning' if policy(@report).edit? %>
    <%= link_to 'Delete', @report, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>